# Files that need to be made
HTML_DIR = page-concepts
HEAD_DIR = include

WEBPAGE_BUTTONS_HTML = $(HTML_DIR)/dpad.html
WEBPAGE_BUTTONS_HEAD = $(HEAD_DIR)/dpad.html.h
WEBPAGE_BUTTONS_NAME = BUTTONS_HTML

# WEBPAGE_NAV_HTML = $(HTML_DIR)/NAV-button.html
# WEBPAGE_NAV_HEAD = $(HEAD_DIR)/NAV-button.html.h

CONVERT_HTML_TO_HEAD = generate_header.py

all: $(WEBPAGE_BUTTONS_HEAD) $(WEBPAGE_NAV_HEAD)

$(WEBPAGE_BUTTONS_HEAD): $(WEBPAGE_BUTTONS_HTML)
	python3 $(CONVERT_HTML_TO_HEAD) $(WEBPAGE_BUTTONS_HTML) $(WEBPAGE_BUTTONS_HEAD) $(BUTTONS_HTML)

$(WEBPAGE_NAV_HEAD): $(WEBPAGE_NAV_HTML)
#	python3 $(CONVERT_HTML_TO_HEAD) $(WEBPAGE_NAV_HTML) $(WEBPAGE_NAV_HEAD)

clean: 
	rm -f $(WEBPAGE_BUTTONS_HEAD)