# Files that need to be made
HTML_DIR = page-concepts
HEAD_DIR = include


WEBPAGE_BUTTONS_NAME = UI_BUTTONS
WEBPAGE_BUTTONS_FILE = dpad.html
WEBPAGE_BUTTONS_HTML = $(HTML_DIR)/$(WEBPAGE_BUTTONS_FILE)
WEBPAGE_BUTTONS_HEAD = $(HEAD_DIR)/$(WEBPAGE_BUTTONS_FILE).h

WEBPAGE_NAV_NAME = NAV_POSITION
WEBPAGE_NAV_FILE = NAV-button.html
WEBPAGE_NAV_HTML = $(HTML_DIR)/$(WEBPAGE_NAV_FILE)
WEBPAGE_NAV_HEAD = $(HEAD_DIR)/$(WEBPAGE_NAV_FILE).h

CONVERT_HTML_TO_HEAD = generate_header.py

all: $(WEBPAGE_BUTTONS_HEAD) $(WEBPAGE_NAV_HEAD)

$(WEBPAGE_BUTTONS_HEAD): $(WEBPAGE_BUTTONS_HTML)
	python3 $(CONVERT_HTML_TO_HEAD) $(WEBPAGE_BUTTONS_HTML) $(WEBPAGE_BUTTONS_HEAD) $(WEBPAGE_BUTTONS_NAME)

$(WEBPAGE_NAV_HEAD): $(WEBPAGE_NAV_HTML)
	python3 $(CONVERT_HTML_TO_HEAD) $(WEBPAGE_NAV_HTML) $(WEBPAGE_NAV_HEAD) $(WEBPAGE_NAV_NAME)

clean: 
	rm -f $(WEBPAGE_BUTTONS_HEAD) $(WEBPAGE_NAV_HEAD)